### ISSUE TITLE
Path was updated to 8.0 and causes incompatibility.

### ISSUE THREAD

**Issue by chrisidefix** [pickleshare/pickleshare#8]
Currently, if you update `path.py` to the latest release it no longer works with `pickleshare`. In particular, when running `ipython` you may receive this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/usr/local/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/site-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: cannot import name path
```

See this commit: https://github.com/jaraco/path.py/commit/62ccb7623d4d048af663f205e21c2ec3f24fa17d

For now, I just downgraded to [path.py 7.7.1](https://github.com/jaraco/path.py/releases/tag/7.7.1), but any chance you will release a fix for this?

**Comment by Michaelizm** [comment]
Yes,Please use "pip install -I path.py==7.7.1" to fix.

**Comment by chrisidefix** [comment]
It might theoretically make sense to update the pypi dependency list to require a version below 8.0 (`install_requires=["path.py<8.0"]`), but I guess that would require creating a new release regardless and it doesn't seem big changes are required to fix this issue. In fact only the [`from path import path as Path`](https://github.com/pickleshare/pickleshare/blob/master/pickleshare.py#L41) needs to be rewritten.

**Comment by Peque** [comment]
I think the best solution is to fix that line and bump the version. I created a pull request some minutes ago (didn't see this conversation discussing about how to solve it). :sweat_smile:

**Comment by chrisidefix** [comment]
The path 8.0 has just been pulled, so for now that pull request should be put on hold.
https://github.com/jaraco/path.py/issues/102#issuecomment-135481508

**Comment by chrisidefix** [comment]
You probably want to add a minimal version requirement to the `path.py` dependency now `path.py >= 6.2` was recommended by @jaraco

**Comment by cdeil** [comment]
I was also running into this error today with Macports .... `ipython` is currently broken:
```
$ ipython 
Traceback (most recent call last):
  File "/opt/local/bin/ipython", line 4, in <module>
    from IPython import start_ipython
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: cannot import name 'path'
```
This is with `path=8.0` and `pickleshare=0.5`.
If someone could fix this for Macports it would be greatly appreciated.
(I currently can't check if there's an open issue in Macports about this ... https://trac.macports.org/ doesn't respond for me.)

**Comment by Peque** [comment]
@cdeil Update `path.py` to version `8.1` or downgrade it to `7.7.1`.

**Comment by jjstickel** [comment]
@cdeil, indeed, it's a pain that macports trac is down. You can fix things yourself locally by copying the Portfile for py-path to your local repository tree and edit it to change the version to 8.1. You will also need to update the checksums. It then works fine.

**Comment by nikolas** [comment]
I used `path.py` version 8.1.1 with pickleshare without a problem.

**Comment by Carreau** [comment]
Has #9 fixed that ?

@minrk should we make a release ?

**Comment by minrk** [comment]
@Carreau yup, pushed 0.6.
